dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - pre-commit run --all-files
  - coverage run --source=libmozdata -m unittest discover tests/ --verbose
  - python setup.py sdist
  - pip install dist/libmozdata-$(cat VERSION).tar.gz
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache: pip
