language: python
python:
  - "3.5"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - flake8 .
  - coverage run --source=libmozdata -m unittest discover tests/ --verbose
  - python setup.py sdist
  - pip install dist/libmozdata-$(cat VERSION).tar.gz
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache: pip
